print('Welcome to the Band Name Generator.')
print('What\'s the name of the city you grew up in?')
userCityName = input()
print('What\'s your pet\'s name?')
userPetName = input()
userBandName = print(f'Your band name could be {userCityName} {userPetName}')
